[project]
name = "aps1-airbnb-eda"
version = "0.1.0"
description = "Análise exploratória dos anúncios do Airbnb em Nova York"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kagglehub",
    "matplotlib",
    "numpy",
    "pandas",
    "scikit-learn",
    "seaborn",
]

[dependency-groups]
dev = [
    "ipykernel",
    "jupyterlab",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "nbconvert",
    "nbformat",
]

[tool.uv]
package = false
